Prefect hw
TiunovNN/hse-bigdata-team2 pull request #9
Opened 2024-12-18 20:11 UTC by BangoSkunk

Добавил ansible playbook для конфигурации prefect
Добавил файл с prefect flow
Обновил readme

2024-12-18 22:40 UTC, TiunovNN requested changes

2024-12-19 16:38 UTC, BangoSkunk commented on playbooks/prefect.service
> +
не могу вообще никак оттестить, поэтому трогать пока не буду

2024-12-19 16:40 UTC, BangoSkunk commented on playbooks/prefect_flow.py
> +    process_data.serve(
я хз, как это отдебажить без серваков, честно говоря

2024-12-19 16:54 UTC, TiunovNN commented on playbooks/configure_prefect.yml
> +          export HDFS_HOST=team-2-nn
Хардкод названия. Нужно так
```yaml
ansible.builtin.blockinfile:
  ...
  block: |
    ...
    export HDFS_HOST={{ namenode }}
vars:
  namenode: "{{ groups['namenodes'] | map('extract', hostvars, 'ansible_hostname') | first }}"
```

2024-12-19 17:43 UTC, TiunovNN requested changes

2024-12-19 17:43 UTC, TiunovNN commented on README.md
> +Поменять хост на ваш в таске
А зачем? Его же можно из переменных ansible достать?

2024-12-19 17:43 UTC, TiunovNN commented on playbooks/prefect_flow.py
> +@task
еще здесь пропустил

2024-12-20 15:25 UTC, merged